version: '3.3'

services:
  drone_controller:
    tty: true
    network_mode: "host"
    build:
      context: .
  broker:
    image: eclipse-mosquitto
    tty: true
    ports:
      - "1883:1883"
      - "9001:9001"