version: '3.3'

services:
  drone_controller:
    container_name: "DC"
    tty: true
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile_x86
  mqtt_broker:
    container_name: "mqtt"
    image: eclipse-mosquitto
    network_mode: "host"
    tty: true
    ports:
      - "1883:1883"
      - "9001:9001"
