FROM mhmdal/olympe_base:x86_v1

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY app/ /app/

USER root
RUN chown olympe /app
USER olympe

ENTRYPOINT ["tail", "-f", "/dev/null"]
