FROM mhmdal/olympe_base:rpi3_v1

COPY requirements.txt /app/requirements.txt
RUN pip install -Iv protobuf==3.19 && pip install --no-cache-dir -r /app/requirements.txt

COPY ./dc_setup.sh ~/dc_setup.sh
COPY app/ /app/

USER root
RUN chmod 777 /app
USER olympe

ENTRYPOINT ["sh", "~/dc_setup.sh"]
